[build]
  base    = "frontend"
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/scores"
  to = "/.netlify/functions/get_ai_scores"
  status = 200
