[build]
  base    = "netlify"
  command = "npm install --prefix ../frontend && npm run build --prefix ../frontend"
  publish = "../frontend/build"
  functions = "functions"

[[redirects]]
  from = "/api/scores"
  to = "/.netlify/functions/get_ai_scores"
  status = 200
