[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/scores"
  to = "/.netlify/functions/get_ai_scores"
  status = 200
